package:
  name: gdal
  version: 2.0.2

source:
    fn: gdal-2.0.2.tar.gz
    url: http://download.osgeo.org/gdal/2.0.2/gdal-2.0.2.tar.gz
    md5: 573865f3f59ba7b4f8f4cddf223b52a5

requirements:
  build:
    - python
    - numpy
    - geos 3.5.0
    - hdf5
    - proj.4
  run:
    - python
    - numpy
    - geos 3.5.0
    - hdf5
    - proj.4

build:
  number: 0

test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo

about:
  home: http://www.gdal.org/
  license: MIT
  summary: The Geospatial Data Abstraction Library (GDAL) Version 2.0.2. Built with all command line tools and with GEOS and HDF5 support.
