package:
  name: gdal
  version: 1.10.1

source:
    fn: gdal-1.10.1.tar.gz
    url: http://download.osgeo.org/gdal/1.10.1/gdal-1.10.1.tar.gz

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy

build:
  number: 0

test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo

about:
  home: http://www.gdal.org/
  license: MIT
  summary: The Geospatial Data Abstraction Library (GDAL) Version 1.10.1.
