package:
  name: gdal
  version: 1.11.3

source:
    fn: gdal-1.11.3.tar.gz
    url: http://download.osgeo.org/gdal/1.11.3/gdal-1.11.3.tar.gz
    md5: 91e245fcc323ff4568aa819e82b4784b

requirements:
  build:
    - python
    - numpy
    - xerces-c
    - geos
    - proj4 4.9.1
    - postgresql [linux]
    - hdf5 1.8.16
    - hdf4
    - json-c
    - openjpeg
    - curl [not win]
    - armadillo [not win]
    - libnetcdf 4.3.3.1 [not osx]
  run:
    - python
    - numpy
    - xerces-c
    - geos
    - proj4 4.9.1
    - postgresql [linux]
    - hdf5 1.8.16
    - hdf4
    - json-c
    - openjpeg
    - curl [not win]
    - armadillo [not win]
    - libnetcdf 4.3.3.1 [not osx]

build:
  number: 0

test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo

about:
  home: http://www.gdal.org/
  license: MIT
  summary: The Geospatial Data Abstraction Library (GDAL) Version 1.11.3. Built with all command line tools and with GEOS and HDF5 support.
