package:
  name: libgdal
  version: 2.0.2

source:
  fn: libgdal-2.0.2.tar.gz
  url: http://download.osgeo.org/gdal/2.0.2/gdal-2.0.2.tar.gz

build:
  number: 0

requirements:
  build:
    - hdf4
    - hdf5
    - geos
    - proj4
    - xerces-c
    - libnetcdf
    - kealib
  run:
    - hdf4
    - hdf5
    - geos
    - proj4
    - xerces-c
    - libnetcdf
    - kealib

about:
  home: http://www.gdal.org/
  license: MIT
